name: portfolio_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  responsive_framework: ^0.1.7
  smooth_page_indicator: ^1.0.0+2 
  font_awesome_flutter: ^10.1.0
  url_launcher: ^6.0.20
  scrollable_positioned_list: ^0.3.5
  animated_text_kit: ^4.2.2
  lottie: ^2.0.0
  google_fonts: ^6.1.0
  path_provider: ^2.1.5
  open_file: ^3.5.10
  open_filex: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/animation/
  